Repository BLRenyi/blry, pull requests merged in 2025-07, with the labels that each got.

#3 Setup pr template
  .github/pull_request_template.md
  .gitignore
  README.md
Labels: dev-setup

#6 Reorder headings and file patterns in the .gitignore file
  .gitignore
Labels: cleanup

#5 Create the minimal Django website backend
  backend/blry_website/__init__.py
  backend/blry_website/asgi.py
  backend/blry_website/settings.py
  backend/blry_website/urls.py
  backend/blry_website/wsgi.py
  backend/manage.py
Labels: dev-setup

#7 Create a demo API with Django REST Framework (DRF)
  backend/api/urls.py
  backend/api/views.py
  backend/blry_website/settings.py
  backend/blry_website/urls.py
Labels: dev-setup

#9 Connect React with Django
  backend/blry_website/settings.py
  frontend/src/App.jsx
Labels: dev-setup

#10 Replace the built-in fetch with axios library
  frontend/package.json
  frontend/src/App.jsx
Labels: enhancement

#11 Init Poetry for Python dependency management
  backend/poetry.lock
  backend/pyproject.toml
Labels: dev-setup

#12 Set up the basic endpoints for Signup/ Login/ Token refresh
  backend/accounts/__init__.py
  backend/accounts/admin.py
  backend/accounts/apps.py
  backend/accounts/migrations/__init__.py
  backend/accounts/models.py
  backend/accounts/serializers.py
  backend/accounts/tests.py
  backend/accounts/urls.py
  backend/accounts/views.py
  backend/blry_website/settings.py
  backend/blry_website/urls.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement

#1 Setup tooling
  .flake8
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc
  README.md
  docs/tooling-setup.md
  eslint.config.js
  package.json
  poetry.lock
  pyproject.toml
  scripts/check_project_consistency.py
  yarn.lock
Labels: dev-setup

#15 Separate tooling files for frontend and backend
  .gitignore
  backend/.flake8
  backend/poetry.lock
  backend/pyproject.toml
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/eslint.config.js
  frontend/yarn.lock
  package.json
  poetry.lock
  pyproject.toml
  yarn.lock
Labels: cleanup

#4 Enhance frontend with toolings and extra display pages
  .flake8
  .gitignore
  .prettierignore
  .prettierrc
  eslint.config.js
  frontend/.env.example
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/react.svg
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.css
  frontend/src/components/Header.jsx
  frontend/src/components/__tests__/Footer.test.jsx
  frontend/src/components/__tests__/Header.test.jsx
  frontend/src/config/__tests__/env.test.js
  frontend/src/config/env.js
  frontend/src/index.css
  frontend/src/layouts/Layout.css
  frontend/src/layouts/Layout.jsx
  frontend/src/main.jsx
  frontend/src/pages/About.css
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/__tests__/Contact.test.jsx
  frontend/src/pages/__tests__/Home.test.jsx
  frontend/src/test/README.md
  frontend/src/test/setup.js
  frontend/vite.config.js
  frontend/vitest.config.js
  frontend/yarn.lock
  package.json
  poetry.lock
  pyproject.toml
  yarn.lock
Labels: dev-setup
